###
GET http://0.0.0.0:8000/

###
GET http://0.0.0.0:8000/dragon/

###
GET http://0.0.0.0:8000/basilisk/0

###
GET http://0.0.0.0:8000/chimera/

###
GET http://0.0.0.0:8000/dragon/0

###
PATCH   http://0.0.0.0:8000/basilisk/0
Content-type: application/json

{
    "name": "Имя",
    "magic": "20",
    "strenght": 20,
    "wingspan": 20
}

###
DELETE    http://0.0.0.0:8000/dragon/6
Content-type: application/json


###
POST  http://0.0.0.0:8000/dragon/
Content-type: application/json

{
    "name": "Гора",
    "weight": 500,
    "description": "змей!",
    "magic": "100",
    "wingspan": 100
}

###
POST  http://0.0.0.0:8000/chimera/
Content-type: application/json
