GET http://127.0.0.1:8000/dragon/

###
GET http://0.0.0.0:8000/dragon/

###
PATCH   http://0.0.0.0:8000/dragon/0
Content-type: application/json

{
    "name": "Змейка",
    "weight": 44,
    "length": 20,
    "height": 20,
    "description": "20",
    "magic": "20"
}

###
POST  http://0.0.0.0:8000/dragon/
Content-type: application/json

{
    "name": "Гора",
    "weight": 500,
    "length": 150,
    "height": 156,
    "description": "змей!",
    "magic": "100"
}















###
GET http://127.0.0.1:8000/api/v1/follow/
Content-type: application/json; charset=utf-8
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjU3MjkyMjQxLCJqdGkiOiJlNzhjZDU1NGM0YTQ0MjQ0YjhiNDAwYWMxMTczMjBiYiIsInVzZXJfaWQiOjF9.QYAEWJJigFy1uWE5FR9m7PIps_XZkjyBZkGbgp3jWwM


###
POST http://127.0.0.1:8000/api/v1/posts/
Content-type: application/json; charset=utf-8
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjU3MjkzNjQzLCJqdGkiOiI2ZmUzOTViNzAyZDU0M2FlYTFlMTZkNTRmNTQwMzM0OCIsInVzZXJfaWQiOjJ9.TT2qiabhONWlGYZvCkPFqtqvUbVaDQ5H-rxhdzLkRnQ

{
  "text": "string55"
}

### Запрос на регистрацию
POST http://127.0.0.1:8000/auth/users/
Content-type: application/json; charset=utf-8

{
  "username": "Dima",
  "password": "0123456789"
}


